[package]
name = "message-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
wasm-bindgen = "0.2.99"
log = "0.4.22"

[profile.release]
debug = 1
split-debuginfo = "packed"