[package]
name = "message-pack-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
message-pack = { path = "../message-pack" }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.99"
